### ISSUE TITLE
Could the pipeline process the spatial deconvolution?

### ISSUE THREAD

**Issue by quangu0925** [DavisLaboratory/GeoMXAnalysisWorkflow#4]
The pipeline is really cool. 
However, I have only seen DEG analysis and gene function analysis. 
Could the pipeline process the spatial deconvolution and differential abundance of cell types?
Thank you!

**Comment by estellad** [comment]
Yes I endorse this suggestion. Nanostring has developed SpatialDecon, but not on class of spe. Would you be interested in incorporating this as the next step?

**Comment by ningbioinfo** [comment]
Hi @quangu0925 and @estellad , sorry for the late reply.
The latest version of standR (in BioC 3.17) have a new function call prepareSpatialDecon, allows it to output the spatialExperiment object to talk to SpatialDecon, will update this workflow github in a few days.
